#!/usr/bin/env python3
"""viz_wife_candidates_allgen.py — EVERYTHING generated by M15 (no real mels).
Query = M15-generated 'wife' (from the chunk_084 sentence). Each candidate = M15-
generated prototype (avg of a few M15 gens of that word). Shows whether M15 produces
DISTINCT mels per word or collapses them. r = cosine(gen-wife, gen-candidate centroid).
Saves outputs/wife_candidates_allgen.png."""
import os, json, numpy as np, torch
import torch.nn.functional as F
import torchaudio
import matplotlib; matplotlib.use('Agg'); import matplotlib.pyplot as plt

from config import CFG
import models as M
import data_io as io

PROOT = '<REPO_ROOT>'
WIDX = os.path.join(PROOT, 'M20_powerline_word_classifier', 'word_index.json')
dev = 'cuda' if torch.cuda.is_available() else 'cpu'
CTX = 0.10; T = 64; NPER = 3
TRUE = 'wife'
CANDS = ['beg', 'platte', 'back', 'dock', 'dive', 'drug', 'bought', 'bet', 'pack', 'debt']

ck = torch.load('outputs/run1/last.pt', map_location=dev, weights_only=False)
model = M.build(CFG).to(dev); model.load_state_dict(ck.get('ema', ck['model'])); model.eval()
mm, ms = ck['mel_mean'], ck['mel_std']

man = json.load(open('full_manifest.json'))
by_chunk = {}
for r in man:
    by_chunk.setdefault(r['chunk'], []).append(r)
occ = json.load(open(WIDX))
def is_test(ch): return int(ch.split('_')[1]) % 12 == 0

def find_utt(ch, ws, we):
    best = None
    for r in by_chunk.get(ch, []):
        if r['start_s'] <= ws and r['end_s'] >= we and 2.0 <= r['dur_s'] <= CFG.max_dur_s:
            if best is None or r['dur_s'] < best['dur_s']:
                best = r
    return best

def norm64(m):
    return F.interpolate(torch.as_tensor(m)[None, None].float(), size=(80, T),
                         mode='bilinear', align_corners=False)[0, 0]
def embed(m64):
    z = m64.reshape(-1); z = z - z.mean(); return z / (z.norm() + 1e-8)

_UC = {}
@torch.no_grad()
def gen_utt(u):
    k = (u['chunk'], round(u['start_s'], 3))
    if k in _UC:
        return _UC[k]
    lag = io.read_lag_ms(CFG.lag_path(u['chunk'])) / 1000.0
    dur = min(u['dur_s'], CFG.max_dur_s)
    raw = io.read_bin_window(CFG.bin_path(u['chunk']), u['start_s'] + lag, dur, CFG.cap_sr).astype(np.float32)
    raw = raw / (np.sqrt(np.mean(raw ** 2)) + 1e-8)
    x = np.zeros(CFG.a_len, np.float32); x[:min(len(raw), CFG.a_len)] = raw[:CFG.a_len]
    g = (model.sample(torch.from_numpy(x)[None].to(dev))[0].float().cpu() * ms + mm)
    _UC[k] = g
    return g

def gen_word_mel(ch, s, e):
    u = find_utt(ch, s, e)
    if u is None:
        return None
    g = gen_utt(u)
    f0 = max(0, int((s - CTX - u['start_s']) * CFG.fps)); f1 = min(g.shape[1], int((e + CTX - u['start_s']) * CFG.fps))
    if f1 - f0 < 3:
        f1 = min(g.shape[1], f0 + 3)
    return norm64(g[:, f0:f1])

def gen_prototype(w, nper=NPER):
    rows = [(c, s, e) for (c, s, e) in occ.get(w, []) if is_test(c)]
    if len(rows) < nper:
        rows += [(c, s, e) for (c, s, e) in occ.get(w, []) if not is_test(c)]
    mels = []
    for (c, s, e) in rows:
        m = gen_word_mel(c, s, e)
        if m is not None:
            mels.append(m)
        if len(mels) >= nper:
            break
    if not mels:
        return None, None
    stack = torch.stack(mels)
    avg = stack.mean(0)
    cen = torch.stack([embed(m) for m in mels]).mean(0)
    return avg.numpy(), (cen / (cen.norm() + 1e-8))

# ── query: M15-gen 'wife' from the chunk_084 sentence (same as before) ──
test = [r for r in man if is_test(r['chunk']) and 2.0 <= r['dur_s'] <= 3.8 and len(r['text'].split()) >= 4]
rng = np.random.RandomState(1); rng.shuffle(test); utt = test[2]
ch, us = utt['chunk'], utt['start_s']
ws, we = [(s, e) for (c, s, e) in occ['wife'] if c == ch and s >= us - 0.05 and e <= utt['end_s'] + 0.05][0]
gen_wife64 = gen_word_mel(ch, ws, we)
gwe = embed(gen_wife64)

panels = [('M15-GEN "wife" (query)', gen_wife64.numpy(), None)]
avg_w, cen_w = gen_prototype(TRUE)
panels.append(('M15-GEN "wife" proto', avg_w, float((gwe @ cen_w).item())))
for w in CANDS:
    avg, cen = gen_prototype(w)
    if avg is None:
        print('skip', w, flush=True); continue
    panels.append((w, avg, float((gwe @ cen).item())))

vmn = min(p[1].min() for p in panels); vmx = max(p[1].max() for p in panels)
ncol = 6; nrow = int(np.ceil(len(panels) / ncol))
fig, axes = plt.subplots(nrow, ncol, figsize=(2.3 * ncol, 2.0 * nrow))
axes = np.array(axes).reshape(-1)
for ax, (title, mel, sc) in zip(axes, panels):
    ax.imshow(mel, origin='lower', aspect='auto', cmap='magma', vmin=vmn, vmax=vmx)
    ax.set_xticks([]); ax.set_yticks([])
    col = '#1b7837' if title.startswith('M15') else 'black'
    t = title if sc is None else f'{title}   r={sc:.2f}'
    ax.set_title(t, fontsize=9, color=col)
for ax in axes[len(panels):]:
    ax.axis('off')
fig.suptitle('ALL M15-GENERATED — "wife" query vs M15-generated prototypes of each candidate word\n'
             'does M15 generate DISTINCT mels per word, or the same blob?  (r = corr to gen-"wife")',
             fontsize=11, fontweight='bold')
fig.tight_layout(rect=[0, 0, 1, 0.90])
fig.savefig('outputs/wife_candidates_allgen.png', dpi=145, bbox_inches='tight')
print('wrote outputs/wife_candidates_allgen.png', flush=True)
print('scores:', [(t, round(s, 3)) for (t, _, s) in panels if s is not None], flush=True)
